### ISSUE TITLE
CI check for EVM Equivalence

### ISSUE THREAD

**Issue by jbowen93** [astriaorg/ethermint#7]
We should make some very basic CI test that checks that blocks/headers/hashes returned from Ethermint are EVM Equivalent. This can be done by:
1. Executing a tx on ethermint
2. Reading a block/header with that tx from ethermint
3. Marshalling the response into a geth struct
4. Rehashing from the geth struct
5. Comparing the hash against what was returned in (2)

https://github.com/jbowen93/curl-test is a very basic starting point

**Comment by joroshiba** [comment]
Agreed on basic test. Long term should we get a workflow running more intense EVM equivalence testing? 

It would be good to know all the ways Ethermint isn't EVM equivalent? It might not be a passing test but the goal would be to get to passing. Setting up regression testing with artifacts basically saying "hey you can't become less EVM equivalent". This is a bigger pull obviously for now just making sure we don't break what we have hacked is good.
